In [1]:
import numpy as np

In [2]:
array1 = np.array(range(30))
array2 = np.array([2,3,5])

# Q1

In [3]:
with open("multi_homework.npz","wb") as f:
    np.savez(f,array1,array2)

# Q2

In [4]:
array3 = np.array([[4,5,6], [1,2,3]])

In [5]:
multi = np.load("multi_homework.npz")

In [6]:
x = multi['arr_0']
y = multi['arr_1']

In [7]:
with open("multi_homework.npz","wb") as f:
    np.savez(f,x,y,array3)

In [8]:
multi = np.load("multi_homework.npz")

In [9]:
multi.files

['arr_0', 'arr_1', 'arr_2']

In [10]:
print(multi['arr_0'])
print(multi['arr_1'])
print(multi['arr_2'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]
[[4 5 6]
 [1 2 3]]
