In [1]:
import numpy as np

In [2]:
array1 = np.array([[10, 8], [3, 5]])

# Q1

In [5]:
A = np.linalg.inv(array1)

In [6]:
A@array1

array([[1., 0.],
       [0., 1.]])

# Q2

In [7]:
w,v = np.linalg.eig(array1)

In [8]:
w

array([13.,  2.])

In [9]:
v

array([[ 0.93632918, -0.70710678],
       [ 0.35112344,  0.70710678]])

# Q3

In [26]:
u,s,vh = np.linalg.svd(array1)

In [27]:
u

array([[-0.91663818, -0.39971796],
       [-0.39971796,  0.91663818]])

In [28]:
s

array([13.94721714,  1.86417116])

In [30]:
vh

array([[-0.74319741, -0.6690722 ],
       [-0.6690722 ,  0.74319741]])